# Generated by Django 5.0 on 2024-01-01 23:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название завода')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('building', models.IntegerField(verbose_name='Номер дома')),
                ('creation_date', models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 2, 2, 5, 5, 465634), null=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Завод',
                'verbose_name_plural': 'Заводы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('model', models.CharField(max_length=100, verbose_name='Модель продукта')),
                ('launch_date', models.DateTimeField(verbose_name='Дата выхода на рынок')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название поставщика')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('building', models.IntegerField(verbose_name='Номер дома')),
                ('debt', models.FloatField(default=0.0, verbose_name='Задолженность')),
                ('creation_date', models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 2, 2, 5, 5, 466634), null=True, verbose_name='Дата создания')),
                ('distributor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='electronet.factory', verbose_name='Поставщик')),
                ('product', models.ManyToManyField(to='electronet.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.AddField(
            model_name='factory',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='electronet.product', verbose_name='Продукт'),
        ),
        migrations.CreateModel(
            name='Businessman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название ИП')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('building', models.IntegerField(verbose_name='Номер дома')),
                ('debt', models.FloatField(default=0.0, verbose_name='Задолженность')),
                ('creation_date', models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 2, 2, 5, 5, 467635), null=True, verbose_name='Дата создания')),
                ('distributor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='electronet.distributor', verbose_name='Завод')),
                ('factory', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='electronet.factory', verbose_name='Поставщик')),
                ('product', models.ManyToManyField(to='electronet.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Индивидуальный предприниматель',
                'verbose_name_plural': 'Индивидуальные предприниматели',
            },
        ),
    ]
