# Generated by Django 5.0 on 2024-01-02 16:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessman',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 2, 19, 23, 18, 134615), null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='businessman',
            name='distributor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='electronet.distributor', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='businessman',
            name='factory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='electronet.factory', verbose_name='Завод'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 2, 19, 23, 18, 133616), null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 2, 19, 23, 18, 132616), null=True, verbose_name='Дата создания'),
        ),
    ]
