# Generated by Django 5.0 on 2024-01-02 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronet', '0002_alter_businessman_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessman',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 2, 21, 43, 13, 862471), null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 2, 21, 43, 13, 861472), null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 2, 21, 43, 13, 860471), null=True, verbose_name='Дата создания'),
        ),
    ]
